# Generated by Django 5.2 on 2025-04-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('borrowed', models.BooleanField(default=False)),
                ('borrow_date', models.DateField(default=None, null=True)),
                ('borrower', models.CharField(default=None, null=True)),
            ],
        ),
    ]
