# Generated by Django 5.2 on 2025-04-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=9999, primary_key=True, serialize=False),
        ),
    ]
